<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>YellowFlareCurse</RootNamespace>
    <AssemblyName>YellowFlareCurse</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.4.5</Version>
    <Authors>gadjed</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.11" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.11" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.11" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(ProjectDir)../Build/SPT/user/mods/YellowFlareCurse" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)../Build/SPT/user/mods/YellowFlareCurse" />
    <Copy SourceFiles="$(ProjectDir)config.json" DestinationFolder="$(ProjectDir)../Build/SPT/user/mods/YellowFlareCurse" />
    <Copy SourceFiles="$(ProjectDir)../LICENSE" DestinationFolder="$(ProjectDir)../Build/SPT/user/mods/YellowFlareCurse" Condition="Exists('$(ProjectDir)../LICENSE')" />
    <Copy SourceFiles="$(ProjectDir)../README.md" DestinationFolder="$(ProjectDir)../Build/SPT/user/mods/YellowFlareCurse" Condition="Exists('$(ProjectDir)../README.md')" />
  </Target>
</Project>
